service: public-slack-tiny-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${env:ENVIRONMENT, 'dev'}
  environment: ${file(env.json)}

plugins:
  - serverless-plugin-typescript

functions:
  microfoxSdk:
    handler: dist/index.wrapperHandler
    events:
      - http:
          path: /api/execute
          method: post
          cors: true
      - http:
          path: /docs.json
          method: get
          cors: true

resources:
  Outputs:
    ApiEndpoints:
      Description: "API Endpoints"
      Value:
        Fn::Join:
          - ""
          - - "API: https://"
            - Ref: "ApiGatewayRestApi"
            - ".execute-api."
            - Ref: "AWS::Region"
            - "/${env:ENVIRONMENT, 'dev'}"