service: public-aws-ses-api

plugins:
  - serverless-plugin-typescript
  - serverless-whitelisting
  - serverless-api-gateway-throttling

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${env:ENVIRONMENT, 'dev'}
  environment: ${file(env.json)}

custom:
  allowedIp: ${env:ALLOWED_IP}

  serverless-whitelisting:
    stage: ${self:provider.stage}
    privateStages:
      - staging
      - production
    netblocks:
      - ${self:custom.allowedIp}

  apiGatewayThrottling:
    maxRequestsPerSecond: 50 # steady-state RPS for entire stage
    maxConcurrentRequests: 20 # burst capacity for entire stage

functions:
  unifiedHandler:
    handler: dist/index.handler
    events:
      - http:
          path: /{functionName}
          method: any
          cors: true
          private: true

resources:
  Outputs:
    ApiEndpoints:
      Description: 'API Endpoints'
      Value:
        Fn::Join:
          - ''
          - - 'API: https://'
            - Ref: 'ApiGatewayRestApi'
            - '.execute-api.'
            - Ref: 'AWS::Region'
            - "/${env:ENVIRONMENT, 'dev'}"
