service: Public-AWS-SES-API

package:
  exclude:
    - venv/**
    - src/**

# Configuration
custom:
  # Get environment from env or default to dev
  stage: ${env:ENVIRONMENT, 'dev'}

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${env:ENVIRONMENT, 'dev'}
  environment: ${file(env.json)}

plugins:
  - serverless-plugin-typescript

functions:
  # Send Single Email
  SendSingleEmail:
    handler: dist/index.SendSingleEmail
    events:
      - http:
          path: /send-single-email
          method: post
          cors: true

  # Send Bulk Email
  SendBulkEmail:
    handler: dist/index.SendBulkEmail
    events:
      - http:
          path: /send-bulk-email
          method: post
          cors: true

  # Documentation
  getDocs:
    handler: dist/index.getDocs
    events:
      - http:
          path: /docs.json
          method: get
          cors: true

# Resources for API Gateway
resources:
  Outputs:
    ApiEndpoints:
      Description: "API Endpoints"
      Value:
        Fn::Join:
          - ""
          - - "API: https://"
            - Ref: "ApiGatewayRestApi"
            - ".execute-api."
            - Ref: "AWS::Region"
            - ".amazonaws.com/${env:ENVIRONMENT, 'dev'}"