name: 'packagefox: build'

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write # Keep for potential future interactions, though not strictly needed for this flow

jobs:
  build:
    if: contains(github.event.pull_request.title, 'packagefox:') && !contains(github.event.pull_request.head.sha, 'skip packagefox')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Read packagefox config
        id: config
        run: |
          CONFIG_FILE=".microfox/packagefox-build.json"
          SHOULD_RUN="false"

          if [ -f "$CONFIG_FILE" ]; then
            if jq -e '.requests | length > 0' "$CONFIG_FILE" > /dev/null; then
              SHOULD_RUN="true"
            else
              echo "Warning: Config file found but 'requests' array is empty."
            fi
          else
            echo "Warning: Config file $CONFIG_FILE not found."
          fi

          echo "should_run=$SHOULD_RUN" >> $GITHUB_OUTPUT

      - name: Generate GitHub App Token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.PACKAGEFOX_APP_ID }}
          private_key: ${{ secrets.PACKAGEFOX_PRIVATE_KEY }}

      - name: Run PackageFox Workflow
        if: steps.config.outputs.should_run == 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          PACKAGEFOX_APP_ID: ${{ secrets.PACKAGEFOX_APP_ID }}
          PACKAGEFOX_PRIVATE_KEY: ${{ secrets.PACKAGEFOX_PRIVATE_KEY }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          # Check for required environment variables
          if [ -z "$OPENAI_API_KEY" ] && [ -z "$ANTHROPIC_API_KEY" ] && [ -z "$GEMINI_API_KEY" ]; then
            echo "Error: At least one of OPENAI_API_KEY, ANTHROPIC_API_KEY, or GEMINI_API_KEY must be set"
            exit 1
          fi

          # Run the workflow script
          cd scripts
          npm install
          npm run workflow:packagefox
          npm run embed:docs

      - name: Check for changes
        id: git-check
        if: steps.config.outputs.should_run == 'true'
        run: |
          git add .
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.config.outputs.should_run == 'true' && steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "packagefox: write: update package files [skip packagefox] [skip ci]"
          git push
